### ISSUE TITLE
ctl commands always run chef zero on port 8999 which can cause port conflicts

### ISSUE THREAD

**Issue by echohack** [chef/omnibus-ctl#34]
If you run a *-ctl command, like `opscode-reporting-ctl reconfigure` it spins up Chef Zero on port 8999 to do the converge.

Unfortunately this causes conflicts with other Chef Zero processes that could be running (say if you wanted to create a Chef Server remotely and already had this port taken).

The fix for this is to simply provide a range of ports when running Chef Zero. Chef Zero can take a range of ports instead of just the default 8999: https://github.com/chef/chef-zero/blob/master/lib/chef_zero/server.rb#L260

As a workaround, you can try to override the chef_zero_port in your configuration so it doesn't conflict as so:

.kitchen.yml

```
  # Leave ports 8999-9000 open for Chef Zero processes running on the server.
  # Not setting this will cause conflicts with Chef Zero processes.
  # Chef processes running on the server are not aware of the provisioner and there
  # is no way to pass a chef zero port range to these processes.
  chef_zero_port: 9001-9999
```

**Comment by smith** [comment]
I wonder if you could also use the socketless mode in 12.3 to not worry about ports at all.

**Comment by echohack** [comment]
@smith Would be cool if ctl commands could do this! :dancer: but I'll look into it as a workaround for our own stuff too.

**Comment by vinyar** [comment]
+1 hitting this bug in Test Kitchen trying to stand up chef server and during installing plugins.
