### ISSUE TITLE
Exclude .xz files from "ctl tail" output

### ISSUE THREAD

**Issue by seelensonne** [chef/omnibus-ctl#46]
Currently, the following archived extension are excluded from `ctl tail` output:
- gzip
- gz
- tgz

It would be nice to also exclude `xz`.

See https://github.com/chef/omnibus-ctl/blob/master/lib/omnibus-ctl.rb#L51:
- Current: `@log_exclude = '(config|lock|@|gzip|tgz|gz)'`
- Suggestion: `@log_exclude = '(config|lock|@|gzip|tgz|gz|xz)'`

**Comment by srenatus** [comment]
@seelensonne this looks like a very reasonable idea -- it's also a good chance to contribute a commit if you'd like. Let me know if you need assistance with the process. 😃
